# Основные понятия линейной алгебры: векторы и действия над ними

In [1]:
import numpy as np


In [2]:
# 2
# Задаём вектор  как одномерный массив numpy с помощью функции np.array.

s = np.array([33, 64, 50, 45])
s
## array([33, 64, 50, 45])

array([33, 64, 50, 45])

In [3]:
# Находим третью координату.

# Помним, что в Python массивы нумеруются с нуля, а не с единицы, поэтому для третьей квартиры нужен элемент массива с номером 2.

s[2]
## 50

50

In [4]:
# 4
# Находим размерность вектора. За размерность отвечает функция len().

len(s)
## 4

4

## БАЗОВЫЕ ОПЕРАЦИИ С ВЕКТОРАМИ

In [5]:
# Сложение и вычитание векторов в Python происходит при помощи знаков + и -. 
# Причём важно задать векторы именно как массивы numpy, а не как обычные списки типа list.

a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
a + b
## array([15, 23, 14,  8])
a - b
## array([ 5, -7, -4, -6])

array([ 5, -7, -4, -6])

In [6]:
# В Python число умножается на массив numpy обычным оператором умножения.

a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c
## array([24. ,  9. , 13.6])

array([24. ,  9. , 13.6])

In [8]:
# Задание 2.5


# Ниже представлены доходы семьи за три месяца.

# Доходы мужа: 120, 150 и 190 тысяч рублей.
# Доходы жены: 130, 130 и 130 тысяч рублей.
# Доходы тёщи: 2, 3 и 2.5 тысячи евро.
# Вводите координаты полученных векторов через запятую (без пробела). Пример ввода ответа: 0,1,1.

# Найдите вектор доходов тёщи в тыс. рублей, если курс евро составляет 72 рубля.
 
# Найдите вектор суммарного дохода семьи в тыс. рублей по месяцам.

m = np.array([120, 150, 190])
zh = np.array([130, 130, 130])
t = np.array([2,3,2.5])

t_rub = t*72
display(t_rub)

sum = m+zh+t_rub
display(sum)

array([144., 216., 180.])

array([394., 496., 500.])

In [ ]:
# В Python линейная комбинация полностью соответствует своему названию 
# и вычисляется как комбинация сложения векторов и умножения вектора на число.

p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u
## array([1800, 3000, 2700])

In [9]:
# 2.7
# Найдите линейную комбинацию векторов  с коэффициентами 2, -3 и 5 соответственно.
x = np.array([4,5])
y = np.array([2,1])
u = np.array([1,0])

s = 2*x + (-3)*y + 5*u
display(s)

array([7, 7])

In [11]:
# 2.8
# Юный предприниматель Вовочка мастерит двигатели на водном топливе и продаёт их. 
# За четыре недели он смастерил 3, 4, 5 и 9 двигателей, а продал 1, 5, 3 и 6 двигателей соответственно.

# На изготовление одного двигателя Вовочка тратит 200 рублей, а продаёт двигатели по 400 рублейза штуку.

# Найдите вектор прибыли (разницу между выручкой и затратами) Вовочки за эти четыре недели.

done = np.array([3,4,5,9])
sold = np.array([1,5,3,6])
trat = 200
k = 400

prib = k*sold - trat*done
prib

array([-200, 1200,  200,  600])

In [12]:
# В Python скалярное произведение векторов вычисляется при помощи функции np.dot():

a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)
## 102.0

102.0

In [13]:
# 2.11
# Найдите скалярное произведение векторов .

x = np.array([4, 5, -1])
y = np.array([2,0,1])
np.dot(x,y)

7

# ВЕКТОРЫ. ПРАКТИКА

В Hut_Paradise_DF представлен фрагмент базы данных агентства «Рай в Шалаше». По строкам расположены квартиры, по столбцам — параметры: арендная плата, общая площадь, количество комнат, этаж, количество показов на две недели и жилая площадь:

In [14]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [17]:
# 3.3
# Найдите вектор параметров квартиры номер 5 (нумерация квартир — с 1). 
# Для преобразования DataFrame в массив numpy можно воспользоваться атрибутом values:

Hut_Paradise_values = Hut_Paradise_DF.values
Hut_Paradise_values[4]

array([40, 33,  1,  6, 20, 16])

In [20]:
# 3.4
# Найдите вектор этажей всех квартир. :
Hut_Paradise_DF['4.Floor'].values

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

In [23]:
# 3.5
# Вычислите вектор нежилой площади:
not_liv_area = Hut_Paradise_DF['2.Area'] - Hut_Paradise_DF['6.Liv.Area']
not_liv_area.values

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

In [27]:
# 3.6
# Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, 
# в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, 
# в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

# Найдите продолжительность просмотров в минутах во всех квартирах за две недели.

time = np.array([10,20,30,15,5,40,20,8,20])

demo = Hut_Paradise_DF['5.Demo two weeks'].values
time@demo

1348

In [30]:
# Дано три вектора:

u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

# 3.7
# Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3

k = 2*v + (-3)*w


In [31]:
# 3.8 
# Будет ли эта комбинация ортогональна вектору u?
np.dot(k,u)

0

# Матрицы

Матрицу можно создать функцией np.matrix() или np.array(). Разницу между двумя этими способами мы обсудим в скринкасте.

За размер матрицы отвечает атрибут shape. 

Матрицы, как и массивы, индексируются с 0, а не с 1. Поэтому для вызова  нужно обратиться к элементу матрицы с номерами .

In [32]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [33]:
A.shape
## (4, 3)
print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])
## a_23= 1 a_32= 3 a_33= 1

a_23= 1 a_32= 3 a_33= 1


# Практика: базовые действия над матрицами

In [59]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [60]:
# 5.1
# Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тёщи в первый, второй и третий столбцы матрицы.

# В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. 
# Пример ввода ответа: 1,1,1.

# Примечание. После того как вы запишете векторы в numpy.array, не забудьте его транспонировать, 
# иначе доходы каждого из членов семьи Ивановых запишутся в строки исходной матрицы.

Inc=np.array([Husband_Income,Wife_Income,Mother_In_Law_Income]).T
Inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [61]:
# 5.2
# Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тёщи в первый, второй и третий столбцы.

# В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов.
# Пример ввода ответа: 1,1,1.

# Примечание. После того как вы запишете векторы в numpy.array, не забудьте его транспонировать, 
# иначе расходы каждого из членов семьи Ивановых запишутся в строки исходной матрицы.

Cons=np.array([Husband_Consumption,Wife_Consumption,Mother_In_Law_Consumption]).T
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [62]:
# 5.3
# Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

# Используйте полученную ранее матрицу Inc, где доходы расположены по столбцам.

# Выберите список элементов из первой строки этой матрицы (строки нумеруются с 1):

Inc_clean = Inc*0.87
Inc_clean

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [63]:
# 5.4
# Вычислите матрицу P, которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами после вычета налога и расходами).

# Выберите список элементов из третьей строки этой матрицы:
P = Inc_clean - Cons
P

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

# Матричное умножение

In [64]:
# В Python матрицы можно умножить с помощью функции np.dot(). При перемене мест сомножителей результат также меняется.

A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [65]:
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [66]:
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

## ТЕНЗОРНОЕ ПРОИЗВЕДЕНИЕ ВЕКТОРОВ

Тензорное произведение — это результат матричного умножения вектора-столбца на вектор-строку. Результатом тензорного произведения является матрица.

# 7. Практика: матричное умножение

In [70]:
# 7.1
# Даны матрица A и вектор х:

A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

# Найдите произведение матрицы A и вектора х в том порядке, в котором их можно умножить.

# В качестве ответа запишите координаты получившегося вектора через запятую, без пробелов. Пример ввода ответа: 1,1

A@x

array([26, 30])

In [71]:
# 7.2
# Даны две матрицы:

A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
# Найдите произведение матриц  и  в том порядке, в котором их можно умножить.

# В качестве ответа через запятую, без пробелов запишите элемент чётвертого столбца первой строки.

B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [74]:
# 7.3
# Дана система векторов:

x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
# Составьте матрицу A, расположив векторы x, y, z в строках. Найдите матрицу Грама G системы векторов x, y, z.

# Чему равна полученная матрица Грама ?
A = np.array([x,y,z])
A.T@A

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [75]:
# В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра. 

# Вам предоставлены две таблицы (DataFrame): Count_DF и Price_DF.

# В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.
# В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [88]:
# 7.4
# Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят салону определённую комиссию.

# Вектор комиссий: 
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

# Выберите координаты вектора прибыли салона:

count = Count_DF.values
price = Price_DF.values

prib = count*price
prib@com

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [99]:
# 7.5
# Найдите вектор прибыли стилистов.

com_stil = np.ones(5)-com
com_stil
prib@com_stil

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

## Обратная матрица. Определитель матрицы

In [100]:
# Обратная матрица в Python вычисляется с помощью функции numpy.linalg.inv():

A = np.matrix('1,2,3; 4,5,6; 7, 8, 10')
np.linalg.inv(A)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

In [103]:
# 8.2
A = np.array([[1,2],[2,5]])
np.linalg.inv(A)

array([[ 5., -2.],
       [-2.,  1.]])

# ОПРЕДЕЛИТЕЛЬ МАТРИЦЫ

In [104]:
# В Python определитель считается с помощью функции np.linalg.det().
A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
print(np.linalg.det(A))
# -3.0000000000009

-3.000000000000001


## СЛАУ. Линейная зависимость векторов. Ранг матрицы. Базис

In [106]:
# Давайте рассмотрим пример того, как вычислить ранг в Python. 
# Для этого в библиотеке numpy существует специальная функция linalg.matrix_rank():

import numpy as np
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))
# 2

2


# 10. Практика: обратная матрица, определитель, ранг

In [107]:
# 10.1
# Дана матрица :
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

# Найдите матрицу, обратную матрице .

# В качестве ответа запишите элемент из первого столбца второй строки, округлив его до трёх знаков после точки-разделителя.
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [108]:
#Дана система векторов:

v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [112]:
# 10.2
# Найдите ранг системы векторов , , , . Для этого создайте матрицу системы векторов. Векторы в матрице расположите в столбцы.

A = np.array([v1, v2, v3, v4]).T
np.linalg.matrix_rank(A)

4

In [115]:
# 10.4
# Найдите матрицу Грама системы векторов , , , : . В качестве ответа запишите элемент из четвёртого столбца первой строки.

G = A.T@A
G

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

In [116]:
# 10.5
# Найдите определитель матрицы Грама  системы , , , . Ответ округлите до целого числа.
np.linalg.det(G)

3716647.9999999995

In [118]:
# 10.7
# Найдите обратную матрицу к матрице Грама  системы , , , . 
# В качестве ответа запишите элемент из первого столбца третьей строки, округлив его до трёх знаков после точки-разделителя.

np.linalg.inv(G)[2,0]

-0.026230625014798285